name: Release

on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: "Run ID of the desired CI run to download artifacts from"
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yaml
          workflow_conclusion: success
          run_id: ${{ github.event.inputs.ci_run_id }}
          path: artifacts
          skip_unpack: true

      - name: List artifacts
        run: |
          echo "### Artifacts ###"
          find artifacts -type f | sort

      - name: Delete old latest release
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 0
          delete_tags: true
          delete_tag_pattern: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for 3s
        run: sleep 3

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest build"
          tag_name: latest
          body_path: ${{ github.workspace }}/.github/release_template.md
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            artifacts/*.zip
